print("Enter your number")
inpnum = input()
print("You entered " , int(inpnum) + 5)
print("Enter first number")
n1 = input()
print("Enter second number")
n2 = input()
print("You got the sum as" , int(n1) + int(n2))